name: Employee Service CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest tests/unit -v

      - name: Run integration tests
        run: pytest tests/integration -v

      - name: Build Docker image
        run: docker build -t employee-service .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::544893998643:role/GitHubActionsEmployeeServiceRole
          aws-region: ap-south-1
